{
  //Mokele Mbembe spawning weight. Default is 1.
  "mbembeWeight": 1,
  //The smallest group size Mokeles can spawn in. Default is 1.
  "mbembeMin": 1,
  //The largest group size Mokeles can spawn in. Default is 1.
  "mbembeMax": 1,
  //Dodo spawning weight. Default is 1.
  "dodoWeight": 1,
  //The smallest group size Dodos can spawn in. Default is 1.
  "dodoMin": 1,
  //The largest group size Dodos can spawn in. Default is 4.
  "dodoMax": 4
}
